### ISSUE TITLE
Unable to load the requested file: inc/estimator.php

### ISSUE THREAD

**Issue by mdunham** [madurapa/sitelink-php#1]
Thank you so much for your code sample do you have the view include for estimator.php? I'm working on a sitelink integration and would love to see how your's works.

**Comment by madurapa** [comment]
Oh sorry, It's just a custom file to do some front-end calculation to see how much space it will need. You can just ignore, I will update the code base.

**Comment by madurapa** [comment]
Can you please check now?

**Comment by mdunham** [comment]
Dude, you freakin rock!
