### ISSUE TITLE
sitelink

### ISSUE THREAD

**Issue by kshipweb** [madurapa/sitelink-php#4]
is this still accurate for the sitelink api as of now? I am testing this and it returns the site location information (home / index) but 404's after hitting continue to step 2. Trying to determine why.

**Comment by madurapa** [comment]
Did you enable mod_rewrite in your web server?

**Comment by kshipweb** [comment]
yes mod_rewrite is enabled: 

 sudo httpd -M |grep rewrite_module
 **rewrite_module (shared)**

**Comment by kshipweb** [comment]
i actually found an issue I had made by not setting the $config['base_url'] correctly to point to the sub directory I am testing in. Now it still shows the index page step 1 and when I hit continue it just stays on the step 1 page. I have verified 100% mod_rewrite is ON.

**Comment by kshipweb** [comment]
i nailed it down to it not working because of the php version being used. We are on 7.3. I changed it to 5.6 for testing and it started working. Will research to bring it up to 7.3.

**Comment by madurapa** [comment]
A very good debugging I would say. I guess we have to upgrade the framework as well. https://codeigniter.com/ in order to get a smooth workflow. Let me know if you need anything from my end.

**Comment by kshipweb** [comment]
looks to be. I am not real familiar with CI but going to research and see what i can do.

**Comment by derekmsheldon** [comment]
@madurapa Does this mean it will not work since the PHP is not updated? You mentioned Code Igniter which I am not familiar with. What can I do to get it up and working properly?

**Comment by madurapa** [comment]
> @madurapa Does this mean it will not work since the PHP is not updated? You mentioned Code Igniter which I am not familiar with. What can I do to get it up and working properly?

Sorry I have missed you. this codebase was built on CI 3 which is not working smoothly on PHP 7 since some of the functions are been abandoned. We have to upgrade to CI 4.
