### ISSUE TITLE
PHP Fix/Update

### ISSUE THREAD

**Issue by derekmsheldon** [madurapa/sitelink-php#5]
After reviewing the other issue, does this mean it will not work since the PHP is not updated? You mentioned Code Igniter which I am not familiar with. What can I do to get it up and working properly?

**Comment by kshipweb** [comment]
I was able to work it with php 5.6 but the code will need to be debugged to work in newer PHP7.3.

**Comment by derekmsheldon** [comment]
Thank you kindly!

**Comment by derekmsheldon** [comment]
Could you contact me via email about this project and possible consideration of some paid work for you on this repo? Many thanks! derek@winston-kennedy.com

**Comment by madurapa** [comment]
I have replied to you in the other thread as well as I have sent you an email too
